import { readFileSync } from 'fs';

interface TocItem {
  title: React.ReactNode;
  url: string;
  depth: number;
}

/**
 * Ensure a plain-string Footnotes entry exists in the TOC when the page has footnotes.
 *
 * rehypeToc may already capture the `<h2 id="footnote-label">` generated by remark-gfm,
 * but its title is a React element (heading JSX) that getTextContent can't render correctly.
 * This replaces any such entry with a plain `{ title: 'Footnotes' }` string, or appends
 * one if rehypeToc didn't capture it.
 *
 * @param file - FumaDocs FileInfo. The runtime object includes `absolutePath`
 *   even though the TypeScript type does not declare it.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function withFootnotesEntry(toc?: TocItem[] | null, file?: any): TocItem[] {
  const items = Array.isArray(toc) ? toc : [];
  const absolutePath: string = file?.absolutePath ?? '';
  // Check if the file has any footnote definitions ([^identifier]:)
  let source: string;
  try {
    source = readFileSync(absolutePath, 'utf-8');
  } catch {
    return items;
  }

  const hasFootnotes = /\[\^[\w-]+\]:/.test(source);
  if (!hasFootnotes) return items;

  const footnoteEntry = { title: 'Footnotes', url: '#footnote-label', depth: 2 };

  // Replace if rehypeToc already captured the heading — its title is a React element
  // that doesn't survive getTextContent correctly. Ensure it's always a plain string.
  const existingIndex = items.findIndex(item => item.url === '#footnote-label');
  if (existingIndex !== -1) {
    const copy = [...items];
    copy[existingIndex] = footnoteEntry;
    return copy;
  }

  return [...items, footnoteEntry];
}
