import { readFileSync } from 'fs';

interface TocItem {
  title: React.ReactNode;
  url: string;
  depth: number;
}

/**
 * Append a Footnotes entry to the TOC if the page source contains footnote definitions.
 *
 * FumaDocs extracts headings via a remark plugin (pre-rehype), so the
 * `<h2 id="footnote-label">Footnotes</h2>` generated by remark-gfm never
 * makes it into page.data.toc. This function adds it manually when needed.
 */
/**
 * @param file - FumaDocs FileInfo. The runtime object includes `absolutePath`
 *   even though the TypeScript type does not declare it.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function withFootnotesEntry(toc: TocItem[], file: any): TocItem[] {
  const absolutePath: string = file?.absolutePath ?? '';
  // Check if the file has any footnote definitions ([^identifier]:)
  let source: string;
  try {
    source = readFileSync(absolutePath, 'utf-8');
  } catch {
    return toc;
  }

  const hasFootnotes = /\[\^[\w-]+\]:/.test(source);
  if (!hasFootnotes) return toc;

  // Don't duplicate if FumaDocs ever starts capturing it
  if (toc.some(item => item.url === '#footnote-label')) return toc;

  return [...toc, { title: 'Footnotes', url: '#footnote-label', depth: 2 }];
}
